# Generated by Django 2.0.2 on 2018-02-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencer', models.CharField(max_length=200)),
                ('inv_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('age_at_occurance', models.IntegerField()),
                ('occ_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdna_variant', models.CharField(max_length=200)),
                ('protein_variant', models.CharField(max_length=200)),
                ('genomic_variant', models.CharField(max_length=200)),
                ('pathogeniticity', models.IntegerField(blank=True, null=True)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Investigation')),
            ],
        ),
        migrations.AddField(
            model_name='occurance',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Patient'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='o_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Occurance'),
        ),
    ]
