# Generated by Django 2.0.2 on 2018-02-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRCA_VarDb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='pathogeniticity',
            new_name='pathogenicity',
        ),
    ]
