# Generated by Django 2.0.2 on 2018-02-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BRCA_VarDb', '0002_auto_20180228_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=200)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refseq_id', models.CharField(max_length=200)),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Gene')),
            ],
        ),
        migrations.AlterField(
            model_name='variant',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRCA_VarDb.Transcript'),
        ),
    ]
