# Generated by Django 2.0.2 on 2018-02-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRCA_VarDb', '0003_auto_20180228_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='i_id',
            new_name='investigation_id',
        ),
        migrations.RenameField(
            model_name='investigation',
            old_name='o_id',
            new_name='occurance_id',
        ),
        migrations.RenameField(
            model_name='occurance',
            old_name='p_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='g_id',
            new_name='gene_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='i_id',
            new_name='transcript_id',
        ),
    ]
