# Generated by Django 2.0.2 on 2018-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRCA_VarDb', '0004_auto_20180228_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='pathogenicity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
